### ISSUE TITLE
Buildpack locks Node v0.10.45?

### ISSUE THREAD

**Issue by mtchllbrrn** [AdmitHub/meteor-buildpack-horse#102]
Am I reading correctly, that this buildpack locks Heroku's Node runtime to v0.10.45? Can we follow Heroku's precedent and allow overriding with `"engines": { "node": "6.2.0" }` in `package.json`?

My Meteor codebase include a few Node worker processes, and it'd be nice if I could use modern Node with ES6. Plus, it'd likely speed up the (currently very slow) deploy process.

**Comment by yourcelf** [comment]
Meteor does not support node > v0.10.45.  See https://github.com/meteor/meteor/issues/5124 and https://forums.meteor.com/t/upgrading-node-js-in-meteor/22741 for reference.  Once meteor supports newer nodejs we can upgrade; until then upgrading could encounter edge cases that break things.

**Comment by mtchllbrrn** [comment]
As soon as I posted this I realized why it's locked at `0.10.45`. My mistake, it's been a long night!

Seeing as that's the case, do you have any pointers for how I might make my worker stack ... work?

**Comment by mtchllbrrn** [comment]
Immediate thoughts are they I could deploy a completely separate Heroku app containing just the workers, but this is kind of clumsy. Perhaps I could modify/create a buildpack that transpiles the workers to ES5? 

I haven't written a buildpack, so I'm not certain this sort of thing is possible.

**Comment by yourcelf** [comment]
Sorry, I don't have much experience with node workers and don't have much advice to give.  I do know that buildpacks can spawn multiple *heroku* worker threads.  The `bin/release` file in a buildpack lists the workers involved.  Theoretically, you should be able to have two different node executables (v0.10 for meteor, v6 for your workers) and spawn both processes in the release.  You'd have to work out the interprocess communication for them.

Transpiling's pretty straightforward, as long as the features you're using are just syntactic and not fundamental changes to process behavior.

**Comment by mtchllbrrn** [comment]
Gotcha. This is very promising as well: https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app

**Comment by SachaG** [comment]
Doesn't Meteor install its own version of Node though? Or is that not applicable in this situation?

**Comment by yourcelf** [comment]
This is basically a judgment call for trying to make deployment as reliable as possible, but keeping the code simple, and minimizing the chance for differences in behavior between prod and dev.

The first judgment call is that we want to build and run with the same version of Node that meteor uses internally.  So for that reason, we don't e.g. run with node v4 or v6, we run with v0.10, same major version that meteor ships with.

Meteor does install its own node binary for development; but after the bundle is built, the "meteor tool" is not involved in running the app anymore, it's run by plain node.  Since we install meteor on the server, we *could* dig into meteor internals and try to find the cryptic path where it puts its node (e.g. `.meteor/packages/meteor-tool/1.3.2_4/mt-os.linux.x86_64/dev_bundle/bin/node`), but that path is undocumented behavior.  So this is the second judgment call: we just install the latest v0.10 to run the app with rather than trying to rely on meteor's behavior for where it stores its node binary.  This means we may not be using the same point-version of node (different point releases of meteor ship with different point releases of node), but if semver is doing what it should, it ought to work.

I'd accept a PR that reliably finds the node and npm binary packaged by meteor, but with the caveat that it needs to be be robust to meteor's changes to that undocumented behavior (e.g. the method [described in this article](https://meteorhacks.com/how-meteor-uses-node/) no longer works).  But I'm more reluctant to default to a different major node version.

It'd be trivial to fork this buildpack to change the node version for running the slug if you prefer that; just change the version string in https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L94.  If it seems like something lots of folks want to do, we could add an environment variable to determine major node version.  But my guess is most folks will want to default to "the same version that meteor uses in dev" rather than running a different version in prod.

**Comment by mtchllbrrn** [comment]
This is something I might look into some time. For now, I've deployed the Node-based workers as a separate Heroku project.

**Comment by yourcelf** [comment]
Looks like meteor recently added support (not yet documented) for invoking its bundled node via `meteor node` and npm via `meteor npm`.  I'll be doing some testing to see if we can just rely on those for both the build and executing the built slug.  Need to make sure it works for projects that target an earlier meteor release.

**Comment by yourcelf** [comment]
Beta branch of this buildpack now uses meteor-packaged npm and node rather than downloading it separately:

    heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta

So if you're using meteor 1.4 beta, you get new npm and new node. Please try it out.

**Comment by merlinpatt** [comment]
Meteor 1.4 is officially out of beta. http://info.meteor.com/blog/announcing-meteor-1.4

**Comment by yourcelf** [comment]
Need to fix #125; then we can merge in beta.

**Comment by yourcelf** [comment]
#130 is finally merged; so we now have full support for Meteor 1.4 and use the node/npm that ship with each release.

**Comment by merlinpatt** [comment]
Does that mean we no longer have to use the `#beta`?
