### ISSUE TITLE
App not starting properly

### ISSUE THREAD

**Issue by myyellowshoe** [AdmitHub/meteor-buildpack-horse#109]
From what I can tell it isn't being deployed properly to heroku, though I think something isn't being included.

`There is no route for the path: /`

Here's the build info, don't see any errors.
https://gist.github.com/myyellowshoe/88e3a9f63d7918098fbdef8e46946a8a

It works great locally. so not sure what happening in the translation. Maybe some files are not getting included in the build?

Running Meteor 1.3.1

**Comment by yourcelf** [comment]
It looks like there are  a large number of missing npm modules.  Did you install using `npm install` without `--save`?  If so, you'll have modules installed locally that are not available on the server, because they aren't listed in package.json.  Did you try following the helpful advice in Meteor's error log that you linked?

```
remote: If you notice problems related to these missing modules, consider running:
remote:
remote:   meteor npm install --save tinyliquid jade then-jade dust dustjs-helpers
remote: dustjs-linkedin swig atpl liquor twig eco jazz jqtpl hamljs hamlet whiskers
remote: haml-coffee hogan.js templayed handlebars pug then-pug qejs walrus mustache
remote: just ect mote toffee dot ractive nunjucks htmling react-tools vash slm emblem
remote: less stylus styl node-sass
```

**Comment by gg2001** [comment]
I had similar issues and I found a solution. I published an article on it: https://medium.com/@gautham.gg/deploy-a-meteor-1-3-application-to-heroku-cda1f68ca20a#.on7al5t2v

**Comment by yourcelf** [comment]
@gg2001 your post says nothing relevant to this issue, and you posted the same comment on multiple issues. Stop that or I'll report your account.

**Comment by myyellowshoe** [comment]
@yourcelf Thanks for the response. Honestly didn't think much of that, as it's a fairly generic warning, listing lots of the front end templating languages and libraries I am using a node email template module for sending emails and that's what's causing the warning.

I'll resolve those warnings and see if that helps.

Could it also be something on how I have my app structured? Maybe some files are not getting included for some reason?

**Comment by yourcelf** [comment]
If the files tracked by git, they're included at least in what the buildpack sees.  Check the output of `git status` and carefully check your `.gitignore` if you're not sure.

**Comment by deborah-ufw** [comment]
I had a similar problem. These steps solved it:

1. npm install and meteor update 
2. check .gitignore file - in my case, "node_modules/" was being ignored 
3. set the $PATH - in terminal: PATH=$PATH:$HOME/.meteor

Also, I deployed on Heroku. Some instructions out there say to set it as "myAppName.herokuapp.com". This causes an error in Heroku, but I was unable to see the error prior to reinstalling npm and updating meteor (logs just showed the Node version error). It is fixed if you prepend, "http://", like so, "http://myAppName.herokuapp.com".

These fixes together fixed my deploy. 

Thank you for the "Horse" build script!

**Comment by yourcelf** [comment]
`node_modules` *should* be ignored.  One should never check `node_modules` into git.  Instead, your `package.json` file should reference everything that needs to be in `node_moduels`.

**Comment by myyellowshoe** [comment]
Agreed, there are times where I've seen it useful, but honestly most of the time it's not the right option.

Good news on my end, I got things working well and running properly!
With a fair amount of certainly I think it was boostrap that was causing the issue.

Boostrap was yelling at me that it couldn't find tether https://github.com/twbs/bootstrap/issues/19005 . This wasn't an issue locally but I think it was causing the issues on heroku. I actually ended up just pulling boostrap, jquery and tether into a custom meteor package so i can start managing js dependencies myself, and pull things directly from npm.

As far as all the other depencices npm was yelling about,  they're not necessary. and I don't want to add all those extra pacakges to my build time. I get that the message is helpful for reference to know what languages it supports, but that sounds like something for the readme.

Anywhos, all is well! thanks @yourcelf !

**Comment by deborah-ufw** [comment]
I'm adding this in case anyone comes back. After reading yourcelf's comment that "node_modules/" should not be checked into .git, I went through a process of getting node_modules back out of my repo, then pushed to heroku. 

But I also had a newrelic add-on that installed to that folder, and I didn't know to reference it in my package.json, so when it went missing deployment failed again because the newrelic add-on could not be found. 

Looks like this is a potential trouble issue when modules install and it's necessary to manually put them in the package.json (or else don't git ignore the node_modules folder). Something to check, if others are running into this or similar deployment issues.
