### ISSUE TITLE
Using a newer version of NPM

### ISSUE THREAD

**Issue by SachaG** [AdmitHub/meteor-buildpack-horse#112]
Apparently the buildpack installs NPM v2.15.1. Is there any way to specify a newer version? I ask because versions pre-3.0 apparently crash when there's a dependency conflict warning, while later versions log out the warning but still let you run the app.

**Comment by yourcelf** [comment]
Yup, the buildpack just uses the version of npm bundled with the same major version of node that meteor uses (v0.10).  No version of meteor ships with a 3.0+ version of npm; so the only way you'd be able to do that in dev is to have two entirely different versions of npm installed on your system -- meteor's pre-3.0 bundled version, and your newer version.

Sounds like a pretty messy workaround -- might be ideal to get upstream to fix the dependency conflicts in the first place, though I understand that's not always practical.  I'd be pretty reluctant to add the complexity of installing a newer npm than what our node version ships with.

If you're comfortable running the slug with a newer version of node (e.g. production app will run with different node version than the dev version meteor uses) you could fork the buildpack and change https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/compile#L94 to install a newer node that ships with a newer npm.  You'd just be risking bugs arising from meteor's code that targets node v0.10 rather than v4 or v6.

**Comment by SachaG** [comment]
Well, it seems my prayers have been answered my the Meteor gods ;)

https://github.com/meteor/meteor/blob/devel/History.md#v134

> The version of npm used by meteor npm and when installing Npm.depends dependencies of Meteor packages has been upgraded from 2.15.1 to 3.9.6, which should lead to much flatter node_modules dependency trees.

**Comment by yourcelf** [comment]
Great!  More impetus for us to switch to the meteor-packaged npm rather than the node-packaged one, so that we can match the version used in dev.

**Comment by yourcelf** [comment]
Beta branch of this buildpack now uses meteor-packaged npm and node rather than downloading it separately:

    heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git#beta

So if you're using meteor 1.4 beta, you get new npm and new node.  Please try it out.

**Comment by yourcelf** [comment]
#130 is finally merged, so you can use the master branch of the buildpack for this now.
