### ISSUE TITLE
How do I specify Node v0.10.41 or later for the build?

### ISSUE THREAD

**Issue by vandretti** [AdmitHub/meteor-buildpack-horse#118]
Yesterday, I was able to build. Today I tried another build and it failed this time. Here's the error log:
-----> Fetching set buildpack https://github.com/AdmitHub/meteor-buildpack-horse.git... done
-----> Node.js app detected
-----> Installing node
-----> Installing meteor
Downloading Meteor distribution
Installation failed.
 !     Push rejected, failed to compile Node.js app

After searching around for another buildpack, it seemed able to build and deployed,  but  the application has error. The heroku logs say "Meteor requires Node v0.10.41 or later". Maybe this is the reason why this buildpack failed. Is there a way to specify Node version v0.10.41 or later?

**Comment by vandretti** [comment]
I used another buildpack that uses Node v0.10.41, and was successfully deployed my app to heroku. Looking at the source, this buildpack returns Node version 0.10.46D. This should have sufficient, but this buildpack didn't work out for me.

**Comment by yourcelf** [comment]
Interesting -- a point release change in node ought not break things, but I'm glad you found a solution.  We're [moving towards](https://github.com/AdmitHub/meteor-buildpack-horse/commits/devel) using the node and npm that are bundled with meteor rather than installing our own separate version, so this problem should go away soon.
