### ISSUE TITLE
Deploy to production?

### ISSUE THREAD

**Issue by patrickml** [AdmitHub/meteor-buildpack-horse#139]
I just noticed the meteor app I deployed with this package is running in Dev. How would I configure it to build for production and minify everything?

**Comment by rfines** [comment]
add the BUILD_OPTIONS --production environment variable

**Comment by yourcelf** [comment]
@rfines: BUILD_OPTIONS only applies to the `meteor build` invocation.  Meteor does not currently support a `--production` flag, so this won't help.  BUILD_OPTIONS is useful for things like `--debug` or `--allow-incompatible-update`.  See `meteor help build` for a list of supported options.

@patrickml: what is the indication that things are not build for production and minifying?  When the buildpack runs, it installs npm packages in two passes.  In the [first pass](https://github.com/AdmitHub/meteor-buildpack-horse/blob/80eaadd412871891ec12aed40be0b3c426cd1762/bin/compile#L158-L162), it simply installs meteor and the development environment necessary for building your app, and that includes dev dependencies.  So you will see npm output indicating installation of any `devDependencies` you include at that point.

The [second pass](https://github.com/AdmitHub/meteor-buildpack-horse/blob/80eaadd412871891ec12aed40be0b3c426cd1762/bin/compile#L189-L195) happens *after* the call to `meteor build`, in order to install npm dependencies on the built slug.  This one runs with the `--production` flag, so only non-dev dependencies are installed.  Meteor ought to take care of minifying anything that is shipped down to the client.

**Comment by patrickml** [comment]
@yourcelf if you go to this site view-source:https://www.votify.us/ you can see that all the js files are individual instead of being minified and concatenated into 1 js file for production

**Comment by yourcelf** [comment]
Interesting; haven't seen that behavior from a built app before. What version of meteor are you targeting (the contents of `.meteor/release`)?

**Comment by patrickml** [comment]
Off the top of my head it's 1.4.1

**Comment by JarnoLeConte** [comment]
I encounter a problem in production mode. The minifiers don't run. I end up with a single JavaScript en a single CSS file which aren't minified, while the minifier packages are added to my project.
I use Meteor 1.4.1.1 and deploy with [dokku](http://dokku.viewdocs.io/dokku/)

**Comment by hazio** [comment]
@patrickml check that you have standard-minifiers installed.
(https://atmospherejs.com/meteor/standard-minifiers)

**Comment by patrickml** [comment]
@hazio I believe this was the issue. Thank you!
