### ISSUE TITLE
Constant H15 Errors

### ISSUE THREAD

**Issue by stolinski** [AdmitHub/meteor-buildpack-horse#160]
##### Type of problem

 - Runtime problem after the build succeeds

##### Summary

I've been running with this build pack for a little while and have been getting constant 

H15 is caused by your server sending incomplete responses after 55 seconds of inactivity:

The app seems to be working fine, but these errors are pretty concerning. Any idea of what could be going on here?

##### Contents of `.meteor/release`

METEOR@1.4.2.6

##### Buildpack version

https://github.com/AdmitHub/meteor-buildpack-horse.git#beta

##### Logs

```
2017-02-17T15:56:48.963916+00:00 heroku[router]: at=info method=GET path="/929b7c96c12afc39a82af97e3a5fa64f493e97e0.js?meteor_js_resource=true" host=getatya.com request_id=8a7efd74-f0b7-49f7-aae9-918b09550e77 fwd="67.6.191.206" dyno=web.1 connect=1ms service=968ms status=200 bytes=1160942
2017-02-17T15:56:54.203645+00:00 heroku[router]: at=info method=GET path="/sockjs/info?cb=a62yspv05r" host=getatya.com request_id=656e3ce4-b71d-4f18-8635-3765a7910699 fwd="67.6.191.206" dyno=web.1 connect=1ms service=5ms status=200 bytes=362
2017-02-17T16:06:24.188346+00:00 heroku[router]: at=error code=H15 desc="Idle connection" method=GET path="/sockjs/955/nbq9eztm/websocket" host=getatya.com request_id=77a211ea-be92-4088-8622-0b48984e7941 fwd="172.58.62.209" dyno=web.1 connect=0ms service=5671798ms status=503 bytes=
2017-02-17T16:38:52.584215+00:00 heroku[router]: at=info method=GET path="/sockjs/info?cb=sbyhn5kcrx" host=getatya.com request_id=8100f39c-bc87-464b-9880-0b71deb006c1 fwd="67.6.191.206" dyno=web.1 connect=0ms service=3ms status=200 bytes=363
```

##### Deployment target

Heroku

**Comment by cbanbury** [comment]
+1 also seeing this

**Comment by yourcelf** [comment]
Is https://stackoverflow.com/questions/13063683/h15-on-heroku-sse-request relevant for you?  Looks like you might be using a bare domain.

**Comment by yourcelf** [comment]
I'm going to close this for now; if this continues to be a problem for folks and evidence points to a buildpack issue then please reopen.

**Comment by arumals** [comment]
this is a recurrent problem for me

**Comment by maxnowack** [comment]
The H15 error occurs, if a client is using long polling. Heroku doesn't fully support long polling (a connection will be cancelled if it exceeds 60 seconds). This is not an issue, because Meteor handles this connection-abort and will open a new connection. The only possibility to get rid of these errors is to use a different hosting provider or to force the clients to use websockets

**Comment by arumals** [comment]
> The H15 error occurs, if a client is using long polling. Heroku doesn't fully support long polling (a connection will be cancelled if it exceeds 60 seconds). This is not an issue, because Meteor handles this connection-abort and will open a new connection. The only possibility to get rid of these errors is to use a different hosting provider or to force the clients to use websockets

thanks for your help... is there any doc/reference about forcing websockets?

thanks

**Comment by maxnowack** [comment]
Not really. You can read the client connection type in `Meteor.connection._stream.socket.protocol`. Websockets are always preferred over long polling. Only if the client browser or the client infrastructure doesn't support websockets, the fallback to long polling is used.

Maybe you can do something like this, to inform and disconnect a client (not tested).
````js
if (Meteor.connection._stream.socket.protocol !== 'websocket') {
  alert('Your browser or your infrastructure does not support websockets. Please use a modern browser or in inform your administrator')
  Meteor.disconnect()
}
````

**Comment by VaughnVernon** [comment]
This is a problem for us using vlingo-http backed by vlingo-wire, which was direct use of Java NIO. We thought it was the infamous Java NIO epoll issue that was fixed by Netty, so we applied Netty's fix to vlingo-wire. We finally gave up trying to solve it with direct NIO and even with incorporating Netty's fix. Thus, we switched to Netty in place of NIO, which works everywhere else, but not on Heroku. Then we tried server socket eager closing to close the socket right after a response to an HTTP request. This also didn't work for us. 

All of the above worked from the beginning on direct AWS use, and continues to work there.

We are now stuck with no clue of what we should do. We would sure like to support Heroku. If you have any clues to share we would much appreciate it.

https://github.com/vlingo
