### ISSUE TITLE
Old Meteor version reused from cache instead of installing app's Meteor version

### ISSUE THREAD

**Issue by tab00** [AdmitHub/meteor-buildpack-horse#162]
##### Type of problem
Deployment not ideal

##### Summary
More recent version of Meteor (1.4.3.1) as used by the app was not installed. Instead, version 1.4.2.7 was found in the cache, skipping Meteor installation.

Target Meteor version printed was also wrong. It seems to have printed its own version, not what was in the app's `.meteor/release` file. Though even if it was correct, there is no logic in the script to install the appropriate version for the app.

Maybe reading the `.meteor/release` file would be a more reliable way to get the app's target Meteor version. Then if it is more recent than the Meteor version found in cache, install the new version.

##### Contents of `.meteor/release`
METEOR@1.4.3.1

##### Buildpack version
https://github.com/AdmitHub/meteor-buildpack-horse.git

##### Logs
```
2017-03-01T11:29:43.41+0700 [STG/0]      OUT -----> Existing meteor installation found, using it.
2017-03-01T11:29:43.41+0700 [STG/0]      ERR ++ METEOR --version
2017-03-01T11:29:43.41+0700 [STG/0]      ERR ++ ARGS=--version
2017-03-01T11:29:43.41+0700 [STG/0]      ERR ++ /tmp/cache/meteor/.meteor/meteor --version
2017-03-01T11:29:46.32+0700 [STG/0]      ERR + echo '-----> Target Meteor version: Meteor 1.4.2.7'
```

**Comment by yourcelf** [comment]
Interesting -- the expected behavior from meteor is that it "self updates" when you invoke it in the context of an app whose `.meteor/release` is newer than the current meteor tool version; in the same way that meteor self-downgrades in the context of an older `.meteor/release`.

The expectation on any system is that there's only one site install of the meteor tool, and that the tool self-adapts to the different versions that different projects might be using.  If that behavior isn't (or is no longer) reliable, we may need to reconsider our approach.

Have you confirmed that meteor is indeed not self-updating in the buildpack when you upgrade your project's release?

**Comment by tab00** [comment]
I have not re-deployed, as I have no need to yet, so I have not confirmed.

When exactly should Meteor self-update? When the app is started?

**Comment by yourcelf** [comment]
On any invocation of the meteor tool within the app directory of an app targeting a newer release, including `meteor --version`.  I just did this test, and it did the expected behavior:

```
mkdir /tmp/meteor-install
curl -sS https://install.meteor.com/?release=1.2.1 | HOME=/tmp/meteor-install /bin/sh
cd ~/meteor-1.4-project/
HOME=/tmp/meteor-install /tmp/meteor-install/.meteor/meteor --version
```
and with that invocation of `meteor --version`, meteor began
```
Updating package catalog                         \
Downloading meteor-tool@1.4.0...           [=============    ]
```
and finally output `Meteor 1.4` as the version.

If for some reason this stops working with a recent meteor release, we definitely want to know, because we're relying on that behavior for getting the correct version of meteor to execute the build.

**Comment by tab00** [comment]
Could you try that with version 1.4.2.7 and the latest?

**Comment by yourcelf** [comment]
1. Create a new project with latest meteor, using the regular system meteor-tool installation (~/.meteor):
```
$ cd ~
$ meteor update
Downloading meteor-tool@1.4.3_1...
...
$ meteor --version
Meteor 1.4.3.1
$ meteor create mbh-1.4.3.1
Created a new Meteor app in 'mbh-1.4.3.1'.                                         

To run your new app:                          
  cd mbh-1.4.3.1                              
  meteor npm install                          
  meteor                                      
...
$ cat mbh-1.4.3.1/.meteor/release
METEOR@1.4.3.1
```
2. Install meteor-tool version 1.4.2.7 in separate location:
```
$ mkdir /tmp/meteor-install
$ curl -sS https://install.meteor.com/?release=1.4.2.7 | HOME=/tmp/meteor-install /bin/sh
Downloading Meteor distribution
######################################################################## 100.0%
...
$ cd ~
$ HOME=/tmp/meteor-install/.meteor/meteor --version
Meteor 1.4.2.7
```

3. Invoke our new meteor 1.4.2.7 inside the project that targets 1.4.3.1:
```
$ cd ~/mbh-1.4.3.1/
$ HOME=/tmp/meteor-install /tmp/meteor-install/.meteor/meteor --version
Downloading meteor-tool@1.4.3_1...        [=========               ] 
Extracting meteor-tool@1.4.3_1...          /
Meteor 1.4.3.1
```

Looks like it's working as expected here. Again, if you can confirm otherwise, we want to know.

**Comment by tab00** [comment]
I think I know what the problem is. The way I deploy is to build locally first (using `meteor build`) then deploy the bundle.

The logic of `meteor --version` seems to be: read the .meteor/release file of an app and print the content to the console; if the file was not found, then print the version of the current Meteor installation.

A pre-built bundle does not have a .meteor/release file. It has a star.json file which contains the target meteor version of the app, but `meteor --version` does not try to read it, and instead prints the version of the existing Meteor installation.

So I think I will simply set `BUILDPACK_CLEAR_CACHE=1` whenever I want to deploy an app with a newer Meteor version.
