### ISSUE TITLE
Buildpack is broken

### ISSUE THREAD

**Issue by alexzaporozhets** [AdmitHub/meteor-buildpack-horse#21]
```
Mar 30 14:54:53 libertyads-pr-43 heroku/web.1:  State changed from crashed to starting 
Mar 30 14:54:56 libertyads-pr-43 heroku/web.1:  Starting process with command `app/.meteor/heroku_build/bin/node app/.meteor/heroku_build/app/main.js` 
Mar 30 14:54:57 libertyads-pr-43 app/web.1:  bash: app/.meteor/heroku_build/bin/node: No such file or directory 
Mar 30 14:54:58 libertyads-pr-43 heroku/web.1:  State changed from starting to crashed 
Mar 30 14:54:58 libertyads-pr-43 heroku/web.1:  Process exited with status 127 
```

**Comment by alexzaporozhets** [comment]
I think we can fix this problem by using absolute paths: 
```
web app/.meteor/heroku_build/bin/node app/.meteor/heroku_build/app/main.js
->
web /app/.meteor/heroku_build/bin/node /app/.meteor/heroku_build/app/main.js
```

**Comment by manuelmateus16** [comment]
I am experiencing the same problem using the buildpack with two different apps.

**Comment by zacharyliu** [comment]
Confirming the same issue here. Potentially related: the buildpack is not installing the Meteor version chosen in the `release` file. Even though v1.0.3.2 is specified, v1.0.5 is installed instead according to Heroku build logs.

**Comment by alexzaporozhets** [comment]
I fixed this issue in am fork (https://github.com/alexzaporozhets/meteor-buildpack-horse)

Also I did https://github.com/AdmitHub/meteor-buildpack-horse/pull/22

**Comment by maxko87** [comment]
@alexzaporozhets thanks!

**Comment by manuelmateus16** [comment]
@alexzaporozhets  thank you, problem fixed!

**Comment by ivankravchenko** [comment]
@alexzaporozhets, thank you!
I hope @yourcelf will accept your pull request to keep buildpack working.

**Comment by yourcelf** [comment]
Is anyone affected by this using the Iron scaffolding tool?  I just merged a PR yesterday from @lirbank to add support for apps built with that tool, which introduced the affected line.

I've nerged #22 for now but would prefer to fix or remove the Iron Scaffolding compatibility if you weren't using that.

**Comment by ivankravchenko** [comment]
I'm not using iron-meteor/iron-cli. I don't get what it does :)

**Comment by lirbank** [comment]
@yourcelf I don't think my [patch](https://github.com/AdmitHub/meteor-buildpack-horse/pull/18/files) introduced the bug. The original code was using a relative path, just as my patch did. I could be wrong, but just looking at the code it appears to be like that.

With regards to `iron cli`, it's just a scaffolding tool to make it easier to organize your app as it grows. It put's your meteor project in the /app/ directory instead of having it on root level. Regardless of iron cli, it would be desirable to give developers freedom to organize it's project structure as he/she pleases. For example you might want to move the Meteor project to a separate folder your git repo, instead of having it in the root - so you can have supporting files, notes, configs, shell scripts, etc in your git repo while keeping them outside of the meteor dir where the bundle is created from at deploy time. Though my patch only allows meteor to be in `/`or `/app/` - ideally the build pack should search the pushed dir structure recursively for the meteor project.

With meteor in the root:
```
/.meteor
/config/myconfig.sh <- this file will NOT be folded into the Meteor bundle as it's an .sh file.
/stuff/experiment.js <-- this file WILL be folded into the Meteor bundle, not desired.
```
With meteor in a separate folder allows a safe super project structure:
```
/app/.meteor
/config/myconfig.sh <-- this file will NOT be folded into the Meteor bundle as it's outside of the meteor dir.
/stuff/experiment.js <-- this file will NOT be folded into the Meteor bundle as it's outside of the meteor dir.
```

Regardless of `iron` I think it would make sense for Horse to allow the meteor project to reside in any subfolder of the git repo.

**Comment by yourcelf** [comment]
I'm afraid your PR did introudce the problem, @lirbank.  

At compile-time, ``bin/release`` seems to execute from somewhere other than the dir ``bin/compile`` executes from.  As a result,  ``[ ! -d .meteor ]`` always evaluates true, even for users not building from an ``iron cli`` app.

The key issue facing ``iron cli`` is that the *source* for the meteor app is in ``app/.meteor`` at build time.  Your patch addresses this in ``bin/compile`` by effectively telling the compile script that what heroku checked out is only the contents of the source ``app`` dir in the source repository.

After compilation, the meteor app's compiled bundle is placed in ``.meteor/heroku_build``.  In the running heroku dyno, this happens to run in ``/app/.meteor/heroku_build``, which is why @alexzaporozhets patch fixed it for us.  There was no problem with a relative path; the problem was that the path was being effectively set to ``$PWD/app/.meteor/heroku_build`` (i.e. ``/app/app/.meteor/heroku_build``) for everyone, instead of ``$PWD/.meteor/heroku_build``.

Since what we're concerned about in ``bin/release`` is the location of the compiled bundle and not the source files, I don't believe there's any difference between ``iron cli`` and other meteor apps at that stage.

I'm reverting the ``iron cli`` changes to ``bin/release``.

**Comment by lirbank** [comment]
Hey, thanks a lot for the detailed info. It all makes sense.

My code in `bin/compile` compiles with the meteor app in / or /app/ but the app fails to start if it's in /app/ without the supporting code I provided for `bin/release` (which has now been reverted). I've made a fix for `bin/compile` to support apps in subdirs (both compile and exec) without messing with `bin/release` - much cleaner. Sending a PR separately. Thanks for the guidance!

**Comment by MitchFortier** [comment]
I'm using Iron Scaffolding. This feature is important to me. Still haven't gotten this build pack to work for me. Getting the same error as listed up top.

**Comment by lirbank** [comment]
@MitchFortier Did you use `https://github.com/lirbank/meteor-buildpack-horse.git` as your buildpack?

**Comment by MitchFortier** [comment]
@lirbank I just finished using your buildpack and it worked great. I set it up as my default going forwarded. It's a great alternative as I've now invested quite a bit of time working with iron-cli and Evented Mind. Thanks for your contribution.
