### ISSUE TITLE
Support for GraphicsMagick

### ISSUE THREAD

**Issue by engelgabriel** [AdmitHub/meteor-buildpack-horse#30]
Can I submit a PR  with an extra optional script to add support to http://www.graphicsmagick.org/ ?

**Comment by AndrewMagliozzi** [comment]
Rather than clog up the build process with something only useful to a few folks, I'd suggest you fork the repo and use that fork as your buildpack_url. If you want, please leave a link in this ticket for others to find.

**Comment by travisdahl** [comment]
Yeah. I am encountering a need for this too. When I add the gm buildpack before this buildpack, the files get placed in the `vendor` directory, and because of that the meteor templating breaks when it sees some html files in there. Same with ImageMagick 

```
vendor/imagemagick/share/doc/ImageMagick-6/www/api/MagickWand/main.html:1:
remote: Can't set DOCTYPE here.  (Meteor sets <!DOCTYPE html> for you)
```

I dont know how to ignore those files without being able to change the directory name. @engelgabriel were you encountering the same problems? If so did you ever make a fork?
