### ISSUE TITLE
Push rejected, Please verify your account to install this add-on plan 

### ISSUE THREAD

**Issue by dheerajbhaskar** [AdmitHub/meteor-buildpack-horse#43]
## Background
I didn't want to add a credit card because I wanted to use the mongolab free plan. I went to mongolab, signed up for a free account and put the proper mongo URL in the config vars. Still got the above error.

## Steps followed
Verbatim what was given in the README.md

## Error
> Push rejected, Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.
com/categories/billing Verify now at https://heroku.com/verify

## Expected behavior
The app to build and deploy properly.

## Temp Worakround
I then changed the buildpack to https://github.com/jordansissel/heroku-buildpack-meteor.git and it worked.
May be there's something they're doing that's not in this buildpack? The reason I'm reporting this issue is because I understand that this repo is maintained more actively.

Feel free to ask for more details

**Comment by yourcelf** [comment]
If I understand it right, you're now using mongolab *without* installing it as an addon via heroku -- that's how you've bypassed the heroku account verification.

With this buildpack, the default is to add mongolab as an addon.  If you do this, it's not necessary to sign up for mongolab separately, and not necessary to manually set the MONGO_URL config var.  But the down side is that heroku demands account verification.

With the way you're doing it, you don't need to verify the account with heroku, but it's up to you to set up a mongolab account and set MONGO_URL.

I'm not sure which experience is more of a pain -- many people will already be using heroku in a way that has required them to add a credit card (either because they use a paid tier, or because they use other addons).  In this case, the addon saves the hassle of setting up a separate mongolab account and manually setting the MONGO_URL.  Your approach will be more friendly for people setting up hobby or dev servers with no intention of switching to paid heroku.

If you'd like to use this buildpack without heroku verification, fork it and modify [bin/release](https://github.com/AdmitHub/meteor-buildpack-horse/blob/master/bin/release) to remove the declaration of the mongolab addon.

**Comment by dheerajbhaskar** [comment]
Thanks for getting back. I'm going to take your suggestion to fork and modify the file you've suggested.

Thanks again.

**Comment by dheerajbhaskar** [comment]
Here's the repo for any future visitor who doesn't need the mongolab addon:
https://github.com/dheerajbhaskar/meteor-buildpack-horse-without-mongolab

**Comment by Faisal-nfl** [comment]
I trying deploy  [parse example app](https://github.com/ParsePlatform/parse-server-example) just for learning purpose and its asking me to provide credit card info
I 'm new to this field, is it possible to use your approach here
kindly elaborate it

**Comment by murtazapithawala** [comment]
Hello friends,
i have change this line
heroku buildpacks:set https://github.com/AdmitHub/meteor-buildpack-horse.git
to 
heroku buildpacks:set https://github.com/dheerajbhaskar/meteor-buildpack-horse-without-mongolab
but when i run the below command
> git push heroku master

remote: Build stream timed out, reverting to polling...
remote: Build output:
remote: undefined method `end_with?' for nil:NilClass
remote: !       Push rejected to myoppo.
remote:To https://git.heroku.com/myoppo.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/myoppo.git'

**Comment by Velody** [comment]
@murtazapithawala That's because probably his version is outdated, if you like to try it, here goes mine: https://github.com/Velody/meteor-buildpack-horse
