### ISSUE TITLE
Update METEOR_SETTINGS at end of build process

### ISSUE THREAD

**Issue by j20** [AdmitHub/meteor-buildpack-horse#45]
Would it be possible to run this command at the end of the build process? 

    heroku config:set METEOR_SETTINGS="$(cat config/production/settings.json)"

This updates the app to use the settings file contained in the newly deployed version of the app.

Currently, an app will continue to use the old settings and this has to be run manually after every deploy to get it to use the new settings file. This can cause a moment of site breakage between when the app finishes building and deploying and when the dev can run this command if there were changes to the settings file.

This is the standard settings file location for Iron CLI apps.

**Comment by yourcelf** [comment]
This sounds like a great idea for an "extra", rather than something to include in the core buildpack.  Different people using this buildpack might have different workflows for maintaining their settings -- we, for example, don't keep settings.json checked into version control, so we'd need something else to maintain settings.

I'd encourage you to fork the buildpack and add a script to the "extras" folder which executes this command.  Since your change is a separate file, it should be trivial to merge any changes we make here into your buildpack without conflicts.

**Comment by j20** [comment]
Thanks for mentioning this! I'll definitely do that in the short term.

I think longer term, if Iron CLI becomes a de facto standard or gets blessed at Meteor CLI, it'd make sense to have the buildpack stick as close to the typical way of things are done with CLI scaffolded app, which would include running this command using the standard settings location, and then having others remove or alter it if their apps varied from the norm.

In either case, whether it becomes part of the buildpack or not, putting this in a separate file for easier merging is a great idea.

I'll close this and use a fork for the time being. But please keep it in mind because I do think Iron CLI will likely be the primary scaffolding tool for the Meteor community.

**Comment by yourcelf** [comment]
Whether or not Iron CLI becomes defacto standard, I don't expect everyone to keep settings.json in git.  Even if the dev names their file ``settings.json`` (as we do), it may contain secrets such as API keys (as ours does), and thus need to be gitignore'd (as ours is).  Some setup where settings are gitignored because they contain secrets is standard practice across basically every web dev framework -- Django, Rails, etc.  So as long as meteor/Iron CLI lacks another canonical way to have ignored secrets, we probably should not expect ``settings.json`` to be in version control where heroku's builder can find it.

**Comment by j20** [comment]
That's fair. I guess I've never encountered that because my secrets are always contained in env variables.

In case it's just a matter of not knowing whether the file exists to not run the command if the file doesn't exist, that could be handled with shell:

    if [ -e "$file_name" ]; then
      echo "File exists"
    fi

I'll trust your judgement. A fork is working fine for me. Cheers
