### ISSUE TITLE
Error using BUILDPACK_PRELAUNCH_METEOR workaround

### ISSUE THREAD

**Issue by cbanbury** [AdmitHub/meteor-buildpack-horse#47]
I'm getting the following error when setting the BUILDPACK_PRELAUNCH_METEOR variable on heroku: 

```
error: ios: platform is not in this project
error: android: platform is not in this project
```

Why is the `remove-platform` command required when using this option?

**Comment by yourcelf** [comment]
See #2 and https://github.com/AdmitHub/meteor-buildpack-horse/commit/648e2ed3a435c87f111e83a858a4f9f25e207357.

The error is not a failure -- e.g. it doesn't result in a non-zero return code, and the buildpack should proceed as expected.  We remove mobile build targets so that people who have added them to their projects can successfully build on heroku with BUILDPACK_PRELAUNCH_METEOR set.  If your build is failing, it is likely for a reason other than those printed errors.

**Comment by rurri** [comment]
I am also able to duplicate this. Adding the platforms in allows build and deploy. Taking them out causes build to crash directly below the error messages:

> error: ios: platform is not in this project
> error: android: platform is not in this project
