### ISSUE TITLE
Compress js and css files after build

### ISSUE THREAD

**Issue by anuragagarwal561994** [AdmitHub/meteor-buildpack-horse#58]
Right now the buildpack is working really nice for me, but my site loads up a lot of js files and css files and even in uncompressed form which takes it a lot of time to load. So I was thinking if this build pack could compress the files I could put them in the cdn and manage my website much faster.

Is there any easy way to do this?

**Comment by yourcelf** [comment]
When you build the project with meteor, all CSS / JS should be compressed into single files.  (Meteor does this with `bundle` during the build process, it's not a specific feature of this buildpack).  Is this not working for you?

Meteor currently doesn't provide easy support for CDN integration.  See [https://groups.google.com/forum/#!msg/meteor-core/XDWx5kscddY/lUby11FNGhEJ](this thread) for discussion of `ROOT_URL_AUTH_PREFIX`, which is an undocumented way to cause the meteor build to use a different URL on the front.  But uploading the built assets to a CDN would still be up to you.

I'm going to close this issue here because I don't see uploading CDN uploading in the near future for the buildpack.  If combining and minifying your JS/CSS isn't working, I suspect it's a problem with your codebase and not the buildpack -- but please do reopen if you think the buildpack is messing something up.

**Comment by yourcelf** [comment]
p.s. you could write your own "extra" script which does CDN uploading after building, and use it with a fork of this buildpack.  In other words:
 1. Set the heroku environment variable with the appropriate `ROOT_URL_AUTH_PREFIX`
 2. Build with this buildpack normally (should create bundled CSS/JS files)
 3. Add an extra script that POST's the appropriate files to your CDN.
