### ISSUE TITLE
Consider dropping phantomjs as a default extra. (bzip2: (stdin) is not a bzip2 file)

### ISSUE THREAD

**Issue by yourcelf** [AdmitHub/meteor-buildpack-horse#76]
phantomjs is required for `spiderable` to work.  But the AJAX Search Specification with _escaped_fragment_ [specified by Google](https://webmasters.googleblog.com/2015/10/deprecating-our-ajax-crawling-scheme.html) has been deprecated.

In short: we can expect Google bot (and maybe other bots?) to be able to index meteor pages without server-side rendering.

Do other search engines depend on _escaped_fragment_?  Any other reason to keep phantomjs as a default?

The only downside to keeping phantomjs is that bitbucket has been an unreliable distribution host recently, leading to some build failures as we try to download it:

    bzip2: (stdin) is not a bzip2 file

**Comment by lirbank** [comment]
Haven't explored it but the [FAQ](https://developers.google.com/webmasters/ajax-crawling/docs/faq#whentousewhich) talks about using `!#` instead of `?_escaped_fragment_` but with Meteor I don't use hashes at all but rather "directory looking" routes/urls (I guess most people do the same).

Will investigate further when I find the time.

**Comment by lpender** [comment]
I'm having this problem pretty constantly as well.

Temporary fix: 

`heroku buildpacks:set https://github.com/jeffminnear/meteor-buildpack-horse`

**Comment by yourcelf** [comment]
Alright, this is fixed in #94 by removing phantomjs.  Anyone still needing phantomjs can find it in the [`phantomjs` branch](https://github.com/AdmitHub/meteor-buildpack-horse/tree/phantomjs).
