### ISSUE TITLE
Failing with bzip2: (stdin) is not a bzip2 file

### ISSUE THREAD

**Issue by jacobmischka** [AdmitHub/meteor-buildpack-horse#83]
My builds keep failing with the error in the title. The code runs locally fine. Full output: https://gist.github.com/jacobmischka/6eee84b766cdb4efe0d268889f20f4de

**Comment by yourcelf** [comment]
The cause of this is that bitbucket.org, which distributes phantomjs, is unreliable.  phantomjs is included as a default extra in this buildpack for use with meteor's `spiderable`.   See #76 for a discussion on dropping phantomjs, since spiderable may not be necessary for search engine visibility anymore.

If you retry the build, it should work eventually -- or, you could fork this buildpack and remove the `phantomjs.sh` extra (or host phantomjs somewhere more reliable yourself and change the URL).

**Comment by jacobmischka** [comment]
Okay, thank you for the explanation!
